version: "3.8"

services:
  python-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./python-api:/app
      - ./lib/models:/app/models
    env_file:
      - ./python-api/.env
    restart: unless-stopped

  nextjs-app:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    env_file:
      - .env.local
    depends_on:
      - python-api
    environment:
      - PYTHON_API_URL=http://python-api:5000

volumes:
  node_modules:
